version: "3.9"

services:
  devopsdb:
    image: jithin56/ekswebapp:dbimage-87
    ports:
      - "3306:3306"
    deploy:
      replicas: 1
    networks:
      - mynetwork


  application:
    image: jithin56/ekswebapp:appimage-87
    ports:
      - "1111:8080"
    deploy:
      replicas: 3
    depends_on:
      - devopsdb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: overlay

